version: '3'

services:
    # Service
    greeter:
        build:
            context: .
            args:
                - SERVICE_NAME=greeter
        restart: on-failure
        # 指定結束容器時，發出 interrupt 訊號 (Ctrl + C)
        # stop_signal: SIGINT
        tty: true
        networks:
            - service_network
        depends_on:
            - registry
            - nsqd
        environment:
            - PROJECT_ENV=dev
            - MICRO_BROKER=nsq
            - MICRO_BROKER_ADDRESS=nsqd:4150
            - MICRO_SERVER_ADDRESS=${MICRO_SERVER_ADDRESS}
            - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
            - MICRO_REGISTER_TTL=${MICRO_REGISTER_TTL}
            - MICRO_REGISTER_INTERVAL=${MICRO_REGISTER_INTERVAL}

    # Data Center
    cache:
        image: redis
        restart: always
        tty: true
        networks:
            - service_network

    db:
        image: mysql
        restart: always
        tty: true
        networks:
            - service_network
        ports:
            - "3306:3306"
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=qwe123

    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
        networks:
            - service_network
        depends_on:
            - db

    # Message Queue
    nsqlookupd:
        image: nsqio/nsq
        command: /nsqlookupd
        networks:
            - service_network
        ports:
            - "4160:4160"
            - "4161:4161"

    nsqd:
        image: nsqio/nsq
        command: /nsqd -lookupd-tcp-address=nsqlookupd:4160 -tcp-address=:4150 -http-address=:4151
        depends_on:
            - nsqlookupd
        networks:
            - service_network
        ports:
            - "4150:4150"
            - "4151:4151"

    nsqadmin:
        image: nsqio/nsq
        command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
        depends_on:
            - nsqlookupd
        networks:
            - service_network
        ports:
            - "4171:4171"

    # Micro Tool
    registry:
        image: progrium/consul:latest
        restart: always
        command: -server -bootstrap -rejoin
        ports:
            - "8500:8500"
        networks:
            - service_network

    proxy:
        image: microhq/micro
        restart: always
        command: proxy
        environment:
            - MICRO_PROXY_ADDRESS=${MICRO_PROXY_ADDRESS}
            - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
            - MICRO_REGISTER_TTL=${MICRO_REGISTER_TTL}
            - MICRO_REGISTER_INTERVAL=${MICRO_REGISTER_INTERVAL}
            - MICRO_ENABLE_STATS=${MICRO_ENABLE_STATS}
        ports:
            - "8501:8501"
        networks:
            - service_network
        depends_on:
            - registry

    web:
        image: microhq/micro
        restart: always
        command: web
        environment:
            - MICRO_WEB_ADDRESS=${MICRO_WEB_ADDRESS}
            - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
            - MICRO_REGISTER_TTL=${MICRO_REGISTER_TTL}
            - MICRO_REGISTER_INTERVAL=${MICRO_REGISTER_INTERVAL}
            - MICRO_ENABLE_STATS=${MICRO_ENABLE_STATS}
        ports:
            - "8502:8502"
        networks:
            - service_network
        depends_on:
            - registry

    api:
        image: microhq/micro
        restart: always
        command: api
        environment:
            - MICRO_API_ADDRESS=${MICRO_API_ADDRESS}
            - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
            - MICRO_REGISTER_TTL=${MICRO_REGISTER_TTL}
            - MICRO_REGISTER_INTERVAL=${MICRO_REGISTER_INTERVAL}
            - MICRO_ENABLE_STATS=${MICRO_ENABLE_STATS}
        ports:
            - "8503:8503"
        networks:
            - service_network
        depends_on:
            - registry


networks:
    service_network:
        driver: bridge
