version: '3'

services:
    # Service
    greeter:
        build:
            context: .
            args:
                - SERVICE_NAME=greeter
        restart: on-failure
        # 指定結束容器時，發出 interrupt 訊號 (Ctrl + C)
        # stop_signal: SIGINT
        tty: true
        networks:
            - service_network
        depends_on:
            - registry
        environment:
            - MICRO_REGISTRY_ADDRESS=${REGISTRY_ADDRESS}
            - MICRO_SERVICE_ADDRESS=${SERVICE_ADDRESS}

    # Data Center
    redis:
        image: redis
        restart: always
        tty: true
        networks:
            - service_network

    mysql:
        image: mysql
        restart: always
        tty: true
        networks:
            - service_network

    # Micro Tool
    registry:
        image: progrium/consul:latest
        restart: always
        command: -server -bootstrap -rejoin
        ports:
            - "8300:8300"
            - "8500:8500"
        networks:
            - service_network

    sidecar:
        image: yam8511/micro
        restart: always
        command: --client=grpc --server=grpc --register_interval=5 --register_ttl=10 --enable_stats sidecar
        environment:
            - MICRO_REGISTRY_ADDRESS=${REGISTRY_ADDRESS}
            - MICRO_SIDECAR_ADDRESS=${PROXY_ADDRESS}
        ports:
            - "8501:8501"
        networks:
            - service_network
        depends_on:
            - registry

    web:
        image: yam8511/micro
        restart: always
        command: --client=grpc --server=grpc --register_interval=5 --register_ttl=10 web
        environment:
            - MICRO_REGISTRY_ADDRESS=${REGISTRY_ADDRESS}
            - MICRO_WEB_ADDRESS=${WEB_ADDRESS}
        ports:
            - "8502:8502"
        networks:
            - service_network
        depends_on:
            - registry


networks:
    service_network:
        driver: bridge
