version: '3'

services:
    # Service
    greeter:
        build:
            context: .
            args:
                - SERVICE_NAME=greeter
        restart: on-failure
        # 指定結束容器時，發出 interrupt 訊號 (Ctrl + C)
        # stop_signal: SIGINT
        tty: true
        networks:
            - service_network
        depends_on:
            - registry
        environment:
            - MICRO_SERVER_ADDRESS=${SERVER_ADDRESS}
            - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
            - MICRO_REGISTER_TTL=${MICRO_REGISTER_TTL}
            - MICRO_REGISTER_INTERVAL=${MICRO_REGISTER_INTERVAL}

    # Data Center
    redis:
        image: redis
        restart: always
        tty: true
        networks:
            - service_network

    mysql:
        image: mysql
        restart: always
        tty: true
        networks:
            - service_network

    # Micro Tool
    registry:
        image: progrium/consul:latest
        restart: always
        command: -server -bootstrap -rejoin
        ports:
            - "8500:8500"
        networks:
            - service_network

    proxy:
        image: microhq/micro
        restart: always
        command: proxy
        environment:
            - MICRO_PROXY_ADDRESS=${MICRO_PROXY_ADDRESS}
            - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
            - MICRO_REGISTER_TTL=${MICRO_REGISTER_TTL}
            - MICRO_REGISTER_INTERVAL=${MICRO_REGISTER_INTERVAL}
            - MICRO_ENABLE_STATS=${MICRO_ENABLE_STATS}
        ports:
            - "8501:8501"
        networks:
            - service_network
        depends_on:
            - registry

    web:
        image: microhq/micro
        restart: always
        command: web
        environment:
            - MICRO_WEB_ADDRESS=${MICRO_WEB_ADDRESS}
            - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
            - MICRO_REGISTER_TTL=${MICRO_REGISTER_TTL}
            - MICRO_REGISTER_INTERVAL=${MICRO_REGISTER_INTERVAL}
            - MICRO_ENABLE_STATS=${MICRO_ENABLE_STATS}
        ports:
            - "8502:8502"
        networks:
            - service_network
        depends_on:
            - registry

    api:
        image: microhq/micro
        restart: always
        command: api
        environment:
            - MICRO_API_ADDRESS=${MICRO_API_ADDRESS}
            - MICRO_REGISTRY_ADDRESS=${MICRO_REGISTRY_ADDRESS}
            - MICRO_REGISTER_TTL=${MICRO_REGISTER_TTL}
            - MICRO_REGISTER_INTERVAL=${MICRO_REGISTER_INTERVAL}
            - MICRO_ENABLE_STATS=${MICRO_ENABLE_STATS}
        ports:
            - "8503:8503"
        networks:
            - service_network
        depends_on:
            - registry


networks:
    service_network:
        driver: bridge
