// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/greeter/greeter.proto

/*
Package greeter is a generated protocol buffer package.

It is generated from these files:
	proto/greeter/greeter.proto

It has these top-level messages:
	PingRequest
	PongResponse
	HelloRequest
	HelloResponse
*/
package greeter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PongResponse struct {
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Environment string `protobuf:"bytes,2,opt,name=environment" json:"environment,omitempty"`
}

func (m *PongResponse) Reset()                    { *m = PongResponse{} }
func (m *PongResponse) String() string            { return proto.CompactTextString(m) }
func (*PongResponse) ProtoMessage()               {}
func (*PongResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PongResponse) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *PongResponse) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting string `protobuf:"bytes,2,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "PingRequest")
	proto.RegisterType((*PongResponse)(nil), "PongResponse")
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Say service

type SayClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PongResponse, error)
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type sayClient struct {
	c           client.Client
	serviceName string
}

func NewSayClient(serviceName string, c client.Client) SayClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "say"
	}
	return &sayClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *sayClient) Ping(ctx context.Context, in *PingRequest, opts ...client.CallOption) (*PongResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Say.Ping", in)
	out := new(PongResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sayClient) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Say.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Say service

type SayHandler interface {
	Ping(context.Context, *PingRequest, *PongResponse) error
	Hello(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterSayHandler(s server.Server, hdlr SayHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Say{hdlr}, opts...))
}

type Say struct {
	SayHandler
}

func (h *Say) Ping(ctx context.Context, in *PingRequest, out *PongResponse) error {
	return h.SayHandler.Ping(ctx, in, out)
}

func (h *Say) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.SayHandler.Hello(ctx, in, out)
}

func init() { proto.RegisterFile("proto/greeter/greeter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x50, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x6d, 0xb5, 0x8a, 0x4e, 0x13, 0x0f, 0x73, 0x2a, 0xf5, 0x52, 0x03, 0x42, 0x41, 0x88, 0xa0,
	0x7f, 0xc2, 0x93, 0x94, 0x16, 0xbc, 0x4a, 0x95, 0xa1, 0x04, 0xda, 0xa4, 0x26, 0xb1, 0xe0, 0xbf,
	0x97, 0x66, 0xb3, 0x4b, 0xf6, 0x94, 0xbc, 0xc7, 0xe3, 0x7d, 0x0c, 0xdc, 0xaf, 0xd6, 0x78, 0xf3,
	0x3c, 0x59, 0x22, 0x4f, 0xf6, 0xf8, 0xca, 0xc0, 0x0a, 0x0e, 0x65, 0xa7, 0xf4, 0xd4, 0xd3, 0xcf,
	0x2f, 0x39, 0x2f, 0x06, 0x60, 0x9d, 0xd9, 0xa1, 0x5b, 0x8d, 0x76, 0x84, 0x0f, 0xc0, 0x1c, 0xd9,
	0x4d, 0x7d, 0xd3, 0xa7, 0x1e, 0x17, 0xaa, 0xf2, 0x26, 0x6f, 0x6f, 0xfb, 0x32, 0x72, 0xef, 0xe3,
	0x42, 0xd8, 0x40, 0x49, 0x7a, 0x53, 0xd6, 0xe8, 0x85, 0xb4, 0xaf, 0x2e, 0x0e, 0x8a, 0x84, 0x12,
	0x02, 0xd8, 0x1b, 0xcd, 0xb3, 0x89, 0x21, 0x88, 0x50, 0x24, 0x66, 0xe1, 0x2f, 0x9e, 0x80, 0x47,
	0x4d, 0x4c, 0xae, 0xe1, 0x26, 0x34, 0x55, 0x7a, 0x8a, 0x9e, 0x27, 0xfc, 0xf2, 0x01, 0x97, 0xc3,
	0xf8, 0x87, 0x8f, 0x50, 0xec, 0xdd, 0x91, 0xc9, 0x64, 0x42, 0xcd, 0x65, 0xba, 0x40, 0x64, 0xd8,
	0xc2, 0x55, 0xb0, 0x46, 0x2e, 0xd3, 0x1a, 0xf5, 0x9d, 0x3c, 0x4b, 0x14, 0xd9, 0xd7, 0x75, 0xb8,
	0xc9, 0xeb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x94, 0x3d, 0x50, 0x32, 0x01, 0x00, 0x00,
}
