// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/greeter/greeter.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	proto/greeter/greeter.proto

It has these top-level messages:
	PingRequest
	PongResponse
	HelloRequest
	HelloResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PongResponse struct {
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName" json:"service_name,omitempty"`
	Environment string `protobuf:"bytes,2,opt,name=environment" json:"environment,omitempty"`
}

func (m *PongResponse) Reset()                    { *m = PongResponse{} }
func (m *PongResponse) String() string            { return proto.CompactTextString(m) }
func (*PongResponse) ProtoMessage()               {}
func (*PongResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PongResponse) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *PongResponse) GetEnvironment() string {
	if m != nil {
		return m.Environment
	}
	return ""
}

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Greeting string `protobuf:"bytes,2,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "pb.PingRequest")
	proto.RegisterType((*PongResponse)(nil), "pb.PongResponse")
	proto.RegisterType((*HelloRequest)(nil), "pb.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "pb.HelloResponse")
}

func init() { proto.RegisterFile("proto/greeter/greeter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0xc6, 0x30,
	0x10, 0x84, 0xfd, 0x6b, 0x15, 0xdd, 0xb6, 0xa8, 0x7b, 0x2a, 0xf5, 0x52, 0x73, 0x12, 0x0a, 0x11,
	0xf4, 0x25, 0x3c, 0x49, 0x69, 0x1f, 0x40, 0x1a, 0x59, 0x4a, 0xa0, 0x4d, 0x62, 0x12, 0x0b, 0xbe,
	0xbd, 0x34, 0xa6, 0x3f, 0x39, 0x25, 0xfb, 0x65, 0xd8, 0x99, 0x09, 0x3c, 0x1a, 0xab, 0xbd, 0x7e,
	0x99, 0x2d, 0x91, 0x27, 0x7b, 0x9c, 0x3c, 0x50, 0xcc, 0x8c, 0x60, 0x15, 0x14, 0xbd, 0x54, 0xf3,
	0x40, 0xdf, 0x3f, 0xe4, 0x3c, 0x1b, 0xa1, 0xec, 0xf5, 0x3e, 0x3a, 0xa3, 0x95, 0x23, 0x7c, 0x82,
	0xd2, 0x91, 0xdd, 0xe4, 0x17, 0x7d, 0xaa, 0x69, 0xa5, 0xfa, 0xd4, 0x9e, 0x9e, 0x6f, 0x87, 0x22,
	0xb2, 0x8f, 0x69, 0x25, 0x6c, 0xa1, 0x20, 0xb5, 0x49, 0xab, 0xd5, 0x4a, 0xca, 0xd7, 0xd9, 0xbf,
	0x22, 0x41, 0x8c, 0x41, 0xf9, 0x4e, 0xcb, 0xa2, 0xa3, 0x09, 0x22, 0xe4, 0xc9, 0xb2, 0x70, 0x67,
	0x1d, 0x54, 0x51, 0x13, 0x9d, 0x1b, 0xb8, 0x09, 0x69, 0xa5, 0x9a, 0xe3, 0xce, 0xf3, 0xfc, 0x2a,
	0xe0, 0x72, 0x9c, 0x7e, 0xb1, 0x83, 0x7c, 0xcf, 0x8e, 0x77, 0xdc, 0x08, 0x9e, 0xb4, 0x68, 0xee,
	0x03, 0x48, 0x7a, 0xb0, 0x0b, 0xe4, 0x70, 0x15, 0x0c, 0x30, 0x3c, 0xa6, 0x79, 0x9a, 0x87, 0x84,
	0x1c, 0x7a, 0x71, 0x1d, 0xfe, 0xe8, 0xed, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x7f, 0xb3, 0x35,
	0x42, 0x01, 0x00, 0x00,
}
